name: Enhancement
description: Propose an enhancement
labels: ["enhancement"]
title: "[ENH]: "
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this enhancement hasn't been already submitted by someone by looking through other open/closed issues

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of the enhancement you would like to see implemented
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the enhancement like links, screenshots etc.
